name: github pages

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          clean: false

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          #mdbook-version: '0.4.10'
          mdbook-version: 'latest'
       
      - name: Build with mdBook
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')
          mdbook build -d ./book/$BRANCH_NAME
#      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          keep_files: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
          
      - name: Generate PDF
        uses: pascalgn/latex-template-action@v1
        with:
          main: book.tex  # Set the main .tex file
          args: -pdf -interaction=nonstopmode -halt-on-error  # pdflatex options

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: book.pdf
          path: book.pdf
